// Shared KEY economics math — used by the UI and (later) the fee bot.
//   feesGenerated = volumeUsd * FEE_RATE            (0.03% of trading volume)
//   feesToKeys    = feesGenerated * FEE_SHARE_TO_KEYS
//   feePerKeySol  = (feesToKeys / solPriceUsd) / max(keys, 1)
//   keyValueSol   = baseKeySol + feePerKeySol

import { notifyPayoutBot } from './payout-notify.functions'

export const ZKEY_MINT = '2QjuLTP2BqEZozJagNQazSTB3LsZ6mhkijHiQ5vGLkUw' // empty = SAMPLE sim
// Fungible KEY pool mint (decimals 0, classic SPL Token) — shown in the footer.
export const KEY_MINT = '6KnZsn8Ej9w7LuyGm9y1eA4Q8T6VSoKBLPSSgq6vjVcx'
// Legacy Metaplex collection from the unique-NFT era — no longer minted into.
export const KEY_COLLECTION_MINT_LEGACY = '63auqENdyHBqshgfJ3pEfXQgHR6UXiHWhcDoLfVxcbg5'
export const TOTAL_SUPPLY = 1_000_000_000
// Burn amount and KEY MC share are SEPARATE knobs:
//   BURN_ZKEY_PER_KEY — how many $ZKEY you burn to mint 1 KEY
//   KEY_MC_SHARE      — base KEY value as a fraction of market cap
export const BURN_ZKEY_PER_KEY = 1_000_000
export const KEY_MC_SHARE = 0.0001 // base KEY value = 0.01% of market cap
export const FEE_RATE = 0.0003 // 0.03% of trading volume becomes fees
export const FEE_SHARE_TO_KEYS = 0.8
export const KEYS_OUTSTANDING_FALLBACK = 0 // until a mint tracker exists

export function baseKeySol(mcSol: number): number {
  return mcSol * KEY_MC_SHARE
}

/** Total fees generated by trading volume, in SOL. */
export function feesFromVolumeSol(volumeUsd: number, solPriceUsd: number): number {
  if (!solPriceUsd) return 0
  return (volumeUsd * FEE_RATE) / solPriceUsd
}

export function feePerKeySol(feesVaultSol: number, keysOutstanding: number): number {
  return (feesVaultSol * FEE_SHARE_TO_KEYS) / Math.max(keysOutstanding, 1)
}

export function keyValueSol(mcSol: number, feesVaultSol: number, keysOutstanding: number): number {
  return baseKeySol(mcSol) + feePerKeySol(feesVaultSol, keysOutstanding)
}

export type LiveMarket = {
  mcUsd: number
  mcSol: number
  solPriceUsd: number
  priceUsd: number
  /** DexScreener 24h volume in USD (not lifetime — label it as 24h in the UI). */
  volumeUsd: number
}

type DexPair = {
  marketCap?: number
  fdv?: number
  priceUsd?: string
  priceNative?: string
  liquidity?: { usd?: number }
  quoteToken?: { symbol?: string }
  volume?: { h24?: number }
}

/**
 * Live market cap from DexScreener. Returns null if no mint or no usable pair —
 * the caller must then show SAMPLE, never a fabricated number.
 */
export async function fetchMarket(mint: string): Promise<LiveMarket | null> {
  if (!mint) return null
  try {
    const res = await fetch(`https://api.dexscreener.com/latest/dex/tokens/${mint}`)
    if (!res.ok) return null
    const json = (await res.json()) as { pairs?: Array<DexPair> }
    const pairs = json.pairs ?? []
    if (pairs.length === 0) return null
    // best pair = deepest liquidity
    const best = pairs.reduce((a, b) => ((b.liquidity?.usd ?? 0) > (a.liquidity?.usd ?? 0) ? b : a))
    const mcUsd = best.marketCap ?? best.fdv
    const priceUsd = Number.parseFloat(best.priceUsd ?? '')
    if (!mcUsd || !Number.isFinite(priceUsd) || priceUsd <= 0) return null

    // SOL price: derive from a SOL-quoted pair (priceUsd / priceNative), else fetch WSOL.
    let solPriceUsd = 0
    const priceNative = Number.parseFloat(best.priceNative ?? '')
    if (
      (best.quoteToken?.symbol ?? '').toUpperCase().includes('SOL') &&
      Number.isFinite(priceNative) &&
      priceNative > 0
    ) {
      solPriceUsd = priceUsd / priceNative
    } else {
      solPriceUsd = (await fetchSolPriceUsd()) ?? 0
    }
    if (!solPriceUsd) return null

    // 24h volume across all pairs of this token (DexScreener has no lifetime volume).
    const volumeUsd = pairs.reduce((sum, p) => sum + (p.volume?.h24 ?? 0), 0)

    return { mcUsd, mcSol: mcUsd / solPriceUsd, solPriceUsd, priceUsd, volumeUsd }
  } catch {
    return null
  }
}

const WSOL = 'So11111111111111111111111111111111111111112'

export async function fetchSolPriceUsd(): Promise<number | null> {
  try {
    const res = await fetch(`https://api.dexscreener.com/latest/dex/tokens/${WSOL}`)
    if (!res.ok) return null
    const json = (await res.json()) as { pairs?: Array<DexPair> }
    const pairs = (json.pairs ?? []).filter((p) => Number.parseFloat(p.priceUsd ?? '') > 0)
    if (pairs.length === 0) return null
    const best = pairs.reduce((a, b) => ((b.liquidity?.usd ?? 0) > (a.liquidity?.usd ?? 0) ? b : a))
    const price = Number.parseFloat(best.priceUsd ?? '')
    return Number.isFinite(price) && price > 0 ? price : null
  } catch {
    return null
  }
}

export type KeyMetrics = {
  feesVaultSol: number
  keysOutstanding: number
  mcSol: number | null
  mcUsd: number | null
  keyValueSol: number | null
  volumeUsd: number | null
  volumeBasis: string | null
  updatedAt: string | null
}

const num = (v: unknown): number | null => {
  if (v === null || v === undefined) return null
  const n = Number(v)
  return Number.isFinite(n) ? n : null
}

/**
 * Live fee vault + keys outstanding + last-known MC snapshot from the single
 * `key_metrics` row (id = 1). An external bot UPDATEs that row (service role);
 * the site only reads it and uses it as fallback when DexScreener is blocked.
 */
export async function fetchKeyMetrics(): Promise<KeyMetrics | null> {
  const { supabase } = await import('@/integrations/supabase/client')
  const { data, error } = await supabase
    .from('key_metrics')
    .select('fees_vault_sol, keys_outstanding, mc_sol, mc_usd, key_value_sol, volume_usd, volume_basis, updated_at')
    .eq('id', 1)
    .maybeSingle()
  if (error || !data) return null
  return {
    feesVaultSol: Number(data.fees_vault_sol ?? 0),
    keysOutstanding: Number(data.keys_outstanding ?? 0),
    mcSol: num(data.mc_sol),
    mcUsd: num(data.mc_usd),
    keyValueSol: num(data.key_value_sol),
    volumeUsd: num(data.volume_usd),
    volumeBasis: (data.volume_basis as string | null) ?? null,
    updatedAt: (data.updated_at as string | null) ?? null,
  }
}

/**
 * MC via our own server proxy first (no CORS / no browser rate limit),
 * falling back to a direct browser fetch. Null when neither works.
 */
export async function fetchMarketLive(mint: string): Promise<LiveMarket | null> {
  if (!mint) return null
  try {
    const res = await fetch(`/api/public/mc-proxy?mint=${encodeURIComponent(mint)}`)
    if (res.ok) {
      const json = (await res.json()) as { market?: LiveMarket | null }
      if (json.market && Number.isFinite(json.market.mcSol)) return json.market
    }
  } catch {
    // fall through to direct fetch
  }
  return fetchMarket(mint)
}

export type Holdings = {
  zkey: number | null
  keys: number | null
  /** Legacy unique KEY NFTs still held — burnable in Step 2. */
  legacyMints?: string[]
}

/** Live wallet holdings via our server route. Null values = lookup unavailable. */
export async function fetchHoldings(wallet: string): Promise<Holdings> {
  if (!wallet) return { zkey: null, keys: null, legacyMints: [] }
  try {
    const res = await fetch(`/api/public/holdings?wallet=${encodeURIComponent(wallet)}`)
    if (!res.ok) return { zkey: null, keys: null, legacyMints: [] }
    const json = (await res.json()) as {
      zkey?: number | null
      keys?: number | null
      legacyMints?: string[]
    }
    return {
      zkey: json.zkey ?? null,
      keys: json.keys ?? null,
      legacyMints: json.legacyMints ?? [],
    }
  } catch {
    return { zkey: null, keys: null, legacyMints: [] }
  }
}

export type RedeemRequest = {
  id: string
  created_at: string
  keys_burned: number
  zec_address: string
  status: string
  zec_txid: string | null
}

/**
 * Queue a real redeem row. The payout bot (service role) fulfills it later —
 * the INSERT is enough on its own. notifyPayoutBot (server fn) additionally
 * wakes the bot instantly when ZKEY_PAYOUT_WEBHOOK_URL/KEY are configured;
 * unset, it no-ops quietly and the bot picks the row up on its ~5 min poll.
 */
export async function queueRedeem(input: {
  solWallet: string
  zecAddress: string
  keysBurned: number
  keyValueSol: number | null
  /** real on-chain KEY burn signature — never fabricated */
  burnTx?: string | null
  /** 'prod' (default) or 'test' — lets the payout bot tell /test rows apart. */
  source?: 'prod' | 'test'
}): Promise<{ ok: boolean; error?: string; notified?: boolean }> {
  const { supabase } = await import('@/integrations/supabase/client')
  const { error } = await supabase.from('redeem_requests').insert({
    sol_wallet: input.solWallet,
    zec_address: input.zecAddress,
    keys_burned: input.keysBurned,
    key_value_sol: input.keyValueSol,
    burn_tx: input.burnTx ?? null,
    status: 'pending',
    source: input.source ?? 'prod',
  })
  if (error) return { ok: false, error: error.message }
  const { notified } = await notifyPayoutBot({ data: input })
  return { ok: true, notified }
}

export async function fetchRedeemQueue(solWallet: string): Promise<Array<RedeemRequest>> {
  const { supabase } = await import('@/integrations/supabase/client')
  const { data, error } = await supabase
    .from('redeem_requests')
    .select('id, created_at, keys_burned, zec_address, status, zec_txid')
    .eq('sol_wallet', solWallet)
    .order('created_at', { ascending: false })
    .limit(10)
  if (error || !data) return []
  return data.map((r: Record<string, unknown>) => ({ ...r, keys_burned: Number(r['keys_burned']) })) as Array<RedeemRequest>
}

