/* eslint-disable */
// @ts-nocheck
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as LaunchpadRouteImport } from './routes/launchpad'
import { Route as TestRouteImport } from './routes/test'
import { Route as ApiPublicBurnKeyRouteImport } from './routes/api/public/burn-key'
import { Route as ApiPublicConfirmMintRouteImport } from './routes/api/public/confirm-mint'
import { Route as ApiPublicConfirmTxRouteImport } from './routes/api/public/confirm-tx'
import { Route as ApiPublicHoldingsRouteImport } from './routes/api/public/holdings'
import { Route as ApiPublicMcProxyRouteImport } from './routes/api/public/mc-proxy'
import { Route as ApiPublicMintKeyRouteImport } from './routes/api/public/mint-key'
import { Route as ApiPublicSyncKeysRouteImport } from './routes/api/public/sync-keys'

const IndexRoute = IndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => rootRouteImport } as any)
const DocsRoute = DocsRouteImport.update({ id: '/docs', path: '/docs', getParentRoute: () => rootRouteImport } as any)
const LaunchpadRoute = LaunchpadRouteImport.update({ id: '/launchpad', path: '/launchpad', getParentRoute: () => rootRouteImport } as any)
const TestRoute = TestRouteImport.update({ id: '/test', path: '/test', getParentRoute: () => rootRouteImport } as any)
const ApiPublicBurnKeyRoute = ApiPublicBurnKeyRouteImport.update({ id: '/api/public/burn-key', path: '/api/public/burn-key', getParentRoute: () => rootRouteImport } as any)
const ApiPublicConfirmMintRoute = ApiPublicConfirmMintRouteImport.update({ id: '/api/public/confirm-mint', path: '/api/public/confirm-mint', getParentRoute: () => rootRouteImport } as any)
const ApiPublicConfirmTxRoute = ApiPublicConfirmTxRouteImport.update({ id: '/api/public/confirm-tx', path: '/api/public/confirm-tx', getParentRoute: () => rootRouteImport } as any)
const ApiPublicHoldingsRoute = ApiPublicHoldingsRouteImport.update({ id: '/api/public/holdings', path: '/api/public/holdings', getParentRoute: () => rootRouteImport } as any)
const ApiPublicMcProxyRoute = ApiPublicMcProxyRouteImport.update({ id: '/api/public/mc-proxy', path: '/api/public/mc-proxy', getParentRoute: () => rootRouteImport } as any)
const ApiPublicMintKeyRoute = ApiPublicMintKeyRouteImport.update({ id: '/api/public/mint-key', path: '/api/public/mint-key', getParentRoute: () => rootRouteImport } as any)
const ApiPublicSyncKeysRoute = ApiPublicSyncKeysRouteImport.update({ id: '/api/public/sync-keys', path: '/api/public/sync-keys', getParentRoute: () => rootRouteImport } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/launchpad': typeof LaunchpadRoute
  '/test': typeof TestRoute
  '/api/public/burn-key': typeof ApiPublicBurnKeyRoute
  '/api/public/confirm-mint': typeof ApiPublicConfirmMintRoute
  '/api/public/confirm-tx': typeof ApiPublicConfirmTxRoute
  '/api/public/holdings': typeof ApiPublicHoldingsRoute
  '/api/public/mc-proxy': typeof ApiPublicMcProxyRoute
  '/api/public/mint-key': typeof ApiPublicMintKeyRoute
  '/api/public/sync-keys': typeof ApiPublicSyncKeysRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/launchpad': typeof LaunchpadRoute
  '/test': typeof TestRoute
  '/api/public/burn-key': typeof ApiPublicBurnKeyRoute
  '/api/public/confirm-mint': typeof ApiPublicConfirmMintRoute
  '/api/public/confirm-tx': typeof ApiPublicConfirmTxRoute
  '/api/public/holdings': typeof ApiPublicHoldingsRoute
  '/api/public/mc-proxy': typeof ApiPublicMcProxyRoute
  '/api/public/mint-key': typeof ApiPublicMintKeyRoute
  '/api/public/sync-keys': typeof ApiPublicSyncKeysRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/launchpad': typeof LaunchpadRoute
  '/test': typeof TestRoute
  '/api/public/burn-key': typeof ApiPublicBurnKeyRoute
  '/api/public/confirm-mint': typeof ApiPublicConfirmMintRoute
  '/api/public/confirm-tx': typeof ApiPublicConfirmTxRoute
  '/api/public/holdings': typeof ApiPublicHoldingsRoute
  '/api/public/mc-proxy': typeof ApiPublicMcProxyRoute
  '/api/public/mint-key': typeof ApiPublicMintKeyRoute
  '/api/public/sync-keys': typeof ApiPublicSyncKeysRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/docs' | '/launchpad' | '/test' | '/api/public/burn-key' | '/api/public/confirm-mint' | '/api/public/confirm-tx' | '/api/public/holdings' | '/api/public/mc-proxy' | '/api/public/mint-key' | '/api/public/sync-keys'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/docs' | '/launchpad' | '/test' | '/api/public/burn-key' | '/api/public/confirm-mint' | '/api/public/confirm-tx' | '/api/public/holdings' | '/api/public/mc-proxy' | '/api/public/mint-key' | '/api/public/sync-keys'
  id: '__root__' | '/' | '/docs' | '/launchpad' | '/test' | '/api/public/burn-key' | '/api/public/confirm-mint' | '/api/public/confirm-tx' | '/api/public/holdings' | '/api/public/mc-proxy' | '/api/public/mint-key' | '/api/public/sync-keys'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRoute
  LaunchpadRoute: typeof LaunchpadRoute
  TestRoute: typeof TestRoute
  ApiPublicBurnKeyRoute: typeof ApiPublicBurnKeyRoute
  ApiPublicConfirmMintRoute: typeof ApiPublicConfirmMintRoute
  ApiPublicConfirmTxRoute: typeof ApiPublicConfirmTxRoute
  ApiPublicHoldingsRoute: typeof ApiPublicHoldingsRoute
  ApiPublicMcProxyRoute: typeof ApiPublicMcProxyRoute
  ApiPublicMintKeyRoute: typeof ApiPublicMintKeyRoute
  ApiPublicSyncKeysRoute: typeof ApiPublicSyncKeysRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': { id: '/'; path: '/'; fullPath: '/'; preLoaderRoute: typeof IndexRouteImport; parentRoute: typeof rootRouteImport }
    '/docs': { id: '/docs'; path: '/docs'; fullPath: '/docs'; preLoaderRoute: typeof DocsRouteImport; parentRoute: typeof rootRouteImport }
    '/launchpad': { id: '/launchpad'; path: '/launchpad'; fullPath: '/launchpad'; preLoaderRoute: typeof LaunchpadRouteImport; parentRoute: typeof rootRouteImport }
    '/test': { id: '/test'; path: '/test'; fullPath: '/test'; preLoaderRoute: typeof TestRouteImport; parentRoute: typeof rootRouteImport }
    '/api/public/burn-key': { id: '/api/public/burn-key'; path: '/api/public/burn-key'; fullPath: '/api/public/burn-key'; preLoaderRoute: typeof ApiPublicBurnKeyRouteImport; parentRoute: typeof rootRouteImport }
    '/api/public/confirm-mint': { id: '/api/public/confirm-mint'; path: '/api/public/confirm-mint'; fullPath: '/api/public/confirm-mint'; preLoaderRoute: typeof ApiPublicConfirmMintRouteImport; parentRoute: typeof rootRouteImport }
    '/api/public/confirm-tx': { id: '/api/public/confirm-tx'; path: '/api/public/confirm-tx'; fullPath: '/api/public/confirm-tx'; preLoaderRoute: typeof ApiPublicConfirmTxRouteImport; parentRoute: typeof rootRouteImport }
    '/api/public/holdings': { id: '/api/public/holdings'; path: '/api/public/holdings'; fullPath: '/api/public/holdings'; preLoaderRoute: typeof ApiPublicHoldingsRouteImport; parentRoute: typeof rootRouteImport }
    '/api/public/mc-proxy': { id: '/api/public/mc-proxy'; path: '/api/public/mc-proxy'; fullPath: '/api/public/mc-proxy'; preLoaderRoute: typeof ApiPublicMcProxyRouteImport; parentRoute: typeof rootRouteImport }
    '/api/public/mint-key': { id: '/api/public/mint-key'; path: '/api/public/mint-key'; fullPath: '/api/public/mint-key'; preLoaderRoute: typeof ApiPublicMintKeyRouteImport; parentRoute: typeof rootRouteImport }
    '/api/public/sync-keys': { id: '/api/public/sync-keys'; path: '/api/public/sync-keys'; fullPath: '/api/public/sync-keys'; preLoaderRoute: typeof ApiPublicSyncKeysRouteImport; parentRoute: typeof rootRouteImport }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute,
  DocsRoute,
  LaunchpadRoute,
  TestRoute,
  ApiPublicBurnKeyRoute,
  ApiPublicConfirmMintRoute,
  ApiPublicConfirmTxRoute,
  ApiPublicHoldingsRoute,
  ApiPublicMcProxyRoute,
  ApiPublicMintKeyRoute,
  ApiPublicSyncKeysRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
